#include "battlecomponents.h"

namespace ChronoShift 
{


  FLX_REFL_REGISTER_START(Action)
    FLX_REFL_REGISTER_PROPERTY(id)
    FLX_REFL_REGISTER_PROPERTY(target)
  FLX_REFL_REGISTER_END;

  FLX_REFL_REGISTER_START(MoveList)
    FLX_REFL_REGISTER_PROPERTY(move_list)
  FLX_REFL_REGISTER_END;


  FLX_REFL_REGISTER_START(CharacterName)
    FLX_REFL_REGISTER_PROPERTY(character_name)
   FLX_REFL_REGISTER_END;

  FLX_REFL_REGISTER_START(CharacterHealth)
    FLX_REFL_REGISTER_PROPERTY(health)
   FLX_REFL_REGISTER_END;

  FLX_REFL_REGISTER_START(CharacterSpeed)
    FLX_REFL_REGISTER_PROPERTY(current_speed)
    FLX_REFL_REGISTER_PROPERTY(base_speed)
  FLX_REFL_REGISTER_END;

  FLX_REFL_REGISTER_START(IsPlayer)
    FLX_REFL_REGISTER_PROPERTY(is_player)
  FLX_REFL_REGISTER_END;

}
